# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  Gripper_Idol_Gear_Joint:
    has_velocity_limits: true
    max_velocity: 1.919862177191
    has_acceleration_limits: false
    max_acceleration: 0
  Gripper_Servo_Gear_Joint:
    has_velocity_limits: true
    max_velocity: 1.919862177191
    has_acceleration_limits: false
    max_acceleration: 0
  Joint_1:
    has_velocity_limits: true
    max_velocity: 1.919862177191
    has_acceleration_limits: false
    max_acceleration: 0
  Joint_2:
    has_velocity_limits: true
    max_velocity: 1.919862177191
    has_acceleration_limits: false
    max_acceleration: 0
  Joint_3:
    has_velocity_limits: true
    max_velocity: 1.919862177191
    has_acceleration_limits: false
    max_acceleration: 0
  Joint_4:
    has_velocity_limits: true
    max_velocity: 1.919862177191
    has_acceleration_limits: false
    max_acceleration: 0
  Joint_5:
    has_velocity_limits: true
    max_velocity: 1.919862177191
    has_acceleration_limits: false
    max_acceleration: 0
  Pivot_Arm_Gripper_Idol_Joint:
    has_velocity_limits: true
    max_velocity: 1.919862177191
    has_acceleration_limits: false
    max_acceleration: 0
  Pivot_Arm_Gripper_Servo_Joint:
    has_velocity_limits: true
    max_velocity: 1.919862177191
    has_acceleration_limits: false
    max_acceleration: 0
  Tip_Gripper_Idol_Joint:
    has_velocity_limits: true
    max_velocity: 1.919862177191
    has_acceleration_limits: false
    max_acceleration: 0
  Tip_Gripper_Servo_Joint:
    has_velocity_limits: true
    max_velocity: 1.919862177191
    has_acceleration_limits: false
    max_acceleration: 0
