gazebo_ros_control:
  pid_gains:
    Joint_1: {p: 100.0, i: 0.01, d: 10.0}
    Joint_2: {p: 100.0, i: 0.01, d: 10.0}
    Joint_3: {p: 100.0, i: 0.01, d: 10.0}
    Joint_4: {p: 100.0, i: 0.01, d: 10.0}
    Joint_5: {p: 100.0, i: 0.01, d: 10.0}
    Gripper_Idol_Gear_Joint: {p: 100.0, i: 0.01, d: 10.0}
    Gripper_Servo_Gear_Joint: {p: 100.0, i: 0.01, d: 10.0}

