sensors:
  - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
    image_topic: /camera/depth_registered/image_raw
    queue_size: 5
    near_clipping_plane_distance: 0.3
    far_clipping_plane_distance: 3.0
    shadow_threshold: 0.2
    padding_scale: 4.0
    padding_offset: 0.1
    filtered_cloud_topic: filtered_cloud
